return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    dashboard = { enabled = true },
    indent = { enabled = true },
    input = { enabled = true },
    notifier = { enabled = true, timeout = 5000 },
    quickfile = { enabled = true },
    scroll = { enabled = true },
    lazygit = { enabled = true },
    statuscolumn = { enabled = true },
    words = { enabled = false },
    animate = { enabled = false },
    toggle = { enabled = false },
    rename = { enabled = false },
    scratch = { enabled = false },
  },
  keys = {
    { "<leader>sc",  function() Snacks.lazygit() end,               desc = "Lazygit" },
    { "<leader>sl",  function() Snacks.lazygit.log() end,           desc = "Lazygit Log (cwd)" },
    { "<leader>snh", function() Snacks.notifier.show_history() end, desc = "Show notifier history" },
    { "<leader>z",   function() Snacks.zen() end,                   desc = "Toggle Zen Mode" },
    { "<leader>.",   function() Snacks.scratch() end,               desc = "Toggle Scratch Buffer" },
    { "<leader>cR",  function() Snacks.rename.rename_file() end,    desc = "Rename File" },
    { "<c-§>",       function() Snacks.terminal() end,              desc = "Toggle Terminal" },
    { "<leader>un",  function() Snacks.notifier.hide() end,         desc = "Dismiss All Notifications" },
  },
}
